name: Lint Python Code

on:
  push:
    branches:
      - main  # or the branch you want to monitor
  pull_request:
    branches:
      - main

jobs:
  pylint:
    name: Run PyLint
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Adjust to your Python version (e.g., 3.9, 3.10)

      # Step 3: Install dependencies (if you have a requirements.txt file)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Install PyLint
      - name: Install PyLint
        run: |
          pip install pylint

      # Step 5: Run PyLint
      - name: Run PyLint
        run: |
          pylint your_package_name  # Replace with the path to your Python code
